# Generated by Django 5.0 on 2025-09-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='security_phrase',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_movie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_question',
            field=models.CharField(blank=True, choices=[('fav_color', 'What is your favorite color?'), ('first_pet', 'What was the name of your first pet?'), ('birth_city', 'In what city were you born?'), ('best_friend', 'What is the first name of your best friend in high school?'), ('mother_maiden', 'What is your mother’s maiden name?')], max_length=50, null=True),
        ),
    ]
