# Generated by Django 5.0 on 2025-09-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_petition_petitionvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='movie',
        ),
    ]
