# Generated by Django 5.0 on 2025-09-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_petition_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitionvote',
            name='vote',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
    ]
